### ISSUE TITLE
PTZ camera control not working

### ISSUE THREAD

**Issue by thhart** [Z-Wave-Me/z-way-issues#114]
I have entered some control commands for a Web-Camera, the video stream is working but the PTZ controls are not working, Z-Wave reports following in the logs, attached is a configuration screenshot.
![z-wave smart home - mozilla firefox_138](https://cloud.githubusercontent.com/assets/2632538/16759360/c4237412-4816-11e6-8858-a9fa436f8d66.png)

```
    2016-07-11 12:31:49.258] [I] [core] Notification: error (module): Error during perform command execution: ReferenceError: http is not defined
    [2016-07-11 12:31:49.268] [I] [core] ReferenceError: http is not defined
        at vDev.controller.devices.create.handler (automation/modules/Camera/index.js:102:21)
        at _.extend.performCommand (automation/classes/VirtualDevice.js:289:37)
        at ZAutomationAPIWebRequest._.extend.performVDevCommandFunc (automation/ZAutomationAPIProvider.js:328:60)
        at ZAutomationAPIWebRequest.handlerFunc (automation/ZAutomationAPIProvider.js:2387:52)
        at ZAutomationAPIWebRequest.ZAutomationWebRequest.handleRequest (automation/WebserverRequestRouter.js:258:41)
        at automation/WebserverRequestRouter.js:32:35
        at WebServer.document_root (automation/Webserver.js:29:11)
```

**Comment by PoltoS** [comment]
This was due to libcurl issue. Fixed a long time ago
