### ISSUE TITLE
z-way crashes during inclusion / interview

### ISSUE THREAD

**Issue by ronie-z-wave** [Z-Wave-Me/z-way-issues#115]
I've tried to include a fibaro flood sensor and got this:

```
[2016-09-05 09:43:17.266] [I] [zway] Removing job: ApplicationStatus Version Get
*** Error in '/opt/z-way-server/z-way-server': malloc(): memory corruption (fast): 0xb34e4878 ***

Program received signal SIGABRT, Aborted.
[Switching to Thread 0xb22ff450 (LWP 362)]
0xb6391f70 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
56      ../nptl/sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) info thread
  Id   Target Id         Frame 
* 14   Thread 0xb22ff450 (LWP 362) "zway/core" 0xb6391f70 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
  10   Thread 0xb2aff450 (LWP 317) "zway/sockets" 0xb642ea64 in select () at ../sysdeps/unix/syscall-template.S:81
  8    Thread 0xb32ff450 (LWP 315) "zway/timers" 0xb6403360 in nanosleep () at ../sysdeps/unix/syscall-template.S:81
  6    Thread 0xb3cff450 (LWP 32740) "zway/webserver" 0xb6986780 in __lll_lock_wait (futex=futex@entry=0x1b950, private=<optimized out>) at ../ports/sysdeps/unix/sysv/linux/arm/nptl/lowlevellock.c:46
  5    Thread 0xb46e6450 (LWP 32697) "zway/core" 0xb6cfb2a4 in v8::internal::MarkCompactCollector::EmptyMarkingDeque() () from ./libs/libv8.so
  4    Thread 0xb4ee6450 (LWP 32696) "v8:MsgDispHelpr" 0xb6985a40 in do_futex_wait (isem=isem@entry=0x5e2cc) at ../nptl/sysdeps/unix/sysv/linux/sem_wait.c:48
  3    Thread 0xb4ef6450 (LWP 32695) "v8:SweeperThrea" 0xb6985a40 in do_futex_wait (isem=isem@entry=0x5e1cc) at ../nptl/sysdeps/unix/sysv/linux/sem_wait.c:48
  2    Thread 0xb56f6450 (LWP 32694) "zway" 0xb6986f60 in accept () at ../sysdeps/unix/syscall-template.S:81
  1    Thread 0xb634b000 (LWP 32609) "z-way-server" 0xb6403360 in nanosleep () at ../sysdeps/unix/syscall-template.S:81
(gdb) bt
#0  0xb6391f70 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0xb6393324 in __GI_abort () at abort.c:89
#2  0xb63cd954 in __libc_message (do_abort=<optimized out>, fmt=0xb6483830 "*** Error in '%s': %s: 0x%s ***\n") at ../sysdeps/posix/libc_fatal.c:175
#3  0xb63d3b80 in malloc_printerr (action=1, str=0xb6483c5c "malloc(): memory corruption (fast)", ptr=<optimized out>) at malloc.c:4996
#4  0xb63d6958 in _int_malloc (av=av@entry=0xb3d00010, bytes=bytes@entry=8) at malloc.c:3359
#5  0xb63d7e18 in __GI___libc_malloc (bytes=8) at malloc.c:2891
#6  0xb58d27d8 in _zway_job_list_append () from ./modules/modzwave.so
#7  0xb58d4214 in _zway_queue_get_jobs () from ./modules/modzwave.so
#8  0xb58dc890 in cleanup_queue () from ./modules/modzwave.so
#9  0xb58deb8c in zway_worker_thread_proc () from ./modules/modzwave.so
#10 0xb697ee90 in start_thread (arg=0xb22ff450) at pthread_create.c:311
#11 0xb6435698 in ?? () at ../ports/sysdeps/unix/sysv/linux/arm/nptl/../clone.S:92 from /lib/arm-linux-gnueabihf/libc.so.6
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
(gdb)
```

This happend three times and more ...
I'm working on RPi B+, UZB v5.06, z-way-server v2.2.4-rc7 synchronized with latest HA dev

**Comment by ronie-z-wave** [comment]
Seems that %CPU usage goes up to 50% and more during inclusion ...  
Also controller reset doesn't help.
This happens also with other devices -.-

**Comment by PoltoS** [comment]
Is it still relevant?

**Comment by ronie-z-wave** [comment]
seems not ... I didn't see this since some months ago
