### ISSUE TITLE
Command is denied by policy?

### ISSUE THREAD

**Issue by bogri** [Z-Wave-Me/z-way-issues#127]
Hi,

after upgrade to the lastest version of the server I suddenly get an error when pressing a button on my NodOn SoftSwitch.

[2017-05-26 14:06:40.394] [I] [core] Notification: error (module): Error during perform command execution: Error: This command is denied by policy
[2017-05-26 14:06:40.402] [I] [core] Error: This command is denied by policy
    at Error (native)
    at CodeDevice.eval (eval at <anonymous> (automation/modules/CodeDevice/index.js:141:14), <anonymous>:1:1)
    at CodeDevice.act (automation/modules/CodeDevice/index.js:141:9)
    at self.controller.devices.create.handler (automation/modules/CodeDevice/index.js:83:22)
    at _.extend.performCommand (automation/classes/VirtualDevice.js:295:37)
    at automation/modules/IfThen/index.js:82:30
    at Array.forEach (native)
    at handlerLevel (automation/modules/IfThen/index.js:55:33)
    at EventEmitter.emit (automation/lib/eventemitter2.js:311:33)
    at _.extend.emit (automation/classes/VirtualDevice.js:321:32)

**Comment by bogri** [comment]
Ah, probably beacuse .syscommands is erased :/

**Comment by bogri** [comment]
that was it actually. Closing issue.
