### ISSUE TITLE
Installation broken on Rapsbian Stretch

### ISSUE THREAD

**Issue by ast** [Z-Wave-Me/z-way-issues#133]
Installation by ```wget -q -O - razberry.z-wave.me/install | sudo bash``` results in a broken installation on Rasbian Stretch because libssl and libcrypto as been upgraded from 1.0.0 to 1.0.2, as such these symbols are missing.

Fixed this by copying previous versions into libs/ but a better solution would be to rebuild for rasbian stretch.

**Comment by psycho0verload** [comment]
+1

**Comment by Jocke-G** [comment]
+1

It is really bad behaivor against your customers that this was not done long time ago.

Please also build it for apt-get, to simplify installation and upgrading!

**Comment by lrascao** [comment]
following @ast 's tip and digging around i made it work like so:

````
wget http://ftp.us.debian.org/debian/pool/main/o/openssl/libssl1.0.0_1.0.2l-1~bpo8+1_armhf.deb
sudo dpkg -i libssl1.0.0_1.0.2l-1~bpo8+1_armhf.deb
````

**Comment by ast** [comment]
It's enough to extract the libssl .so files into libs of the zwave-me installation folder. No need to install could lead to potential conflicts when building other software.

I'm amazed they haven't responded to this bug report yet.

**Comment by lrascao** [comment]
Bumping a patch version should be fine.
My guess is they've got their plate full right now handling load issues on the backend

**Comment by audungk** [comment]
Are anyone actually able to run `wget -q -O - razberry.z-wave.me/install | sudo bash`? On a pi3 running jessie, the script never executes, and there is no response from browser contacting razberry.z-wave.me either

**Comment by RandomReaper** [comment]
After fixing the libssl problem, here is another one : 
```
==> /var/log/z-way-server.log <==
[2018-03-06 12:50:27.088] [I] [core] Executing script: /*** Z-Way Home Automation Engine main executable ***************************** ...
[2018-03-06 12:50:27.091] [I] [core] Executing script: // Comon utilities and functions ...
[2018-03-06 12:50:27.098] [I] [core] Executing script: // This script transforms old formats to new ...
[2018-03-06 12:50:27.138] [I] [core] Executing script: /*! EventEmitter2 https://github.com/hij1nx/EventEmitter2 Copyright (c) 2013 hij1nx Licensed under the MIT license.*/ ...
[2018-03-06 12:50:27.158] [I] [core] Executing script: //     Underscore.js 1.8.3 ...
[2018-03-06 12:50:27.182] [I] [core] Executing script: /*! Papa Parse v4.1.2 https://github.com/mholt/PapaParse */ ...
[2018-03-06 12:50:27.208] [I] [core] Executing script: /* @license zlib.js 2012 - imaya [ https://github.com/imaya/zlib.js ] The MIT License */ ...
[2018-03-06 12:50:27.227] [I] [core] Executing script: // BAOS_API_2011_01_29_001 ...
[2018-03-06 12:50:27.228] [I] [core] Executing script: // Converts IntelHex into binary 128 kB file ...
[2018-03-06 12:50:27.229] [I] [core] Executing script: // Public domain version of Base64 encoder/decoder found somewhere in the Internet ...
[2018-03-06 12:50:27.235] [I] [core] Executing script: //--------------------------------------------------------------------- ...
[2018-03-06 12:50:27.252] [I] [core] Executing script: /* ...
[2018-03-06 12:50:27.255] [I] [core] Executing script: /*** Z-Way HA Virtual Device base class *************************************** ...
[2018-03-06 12:50:27.259] [I] [core] Executing script: /*** Z-Way DevicesCollection class ************************************ ...
[2018-03-06 12:50:27.281] [I] [core] Executing script: /*** Z-Way HA Controller class module ***************************************** ...
[2018-03-06 12:50:27.285] [I] [core] Executing script: /*** Automation Webserver Auth Controller ************************************* ...
[2018-03-06 12:50:27.286] [I] [core] Executing script: /*** Z-Way HA Automation module base class ************************************ ...
[2018-03-06 12:50:27.288] [I] [core] Executing script: /*** Initialize Webserver and Handlers ***************************************** ...
[2018-03-06 12:50:27.296] [E] [core] result: Error: ReferenceError: WebServer is not defined
    at automation/Webserver.js:10:10
    at automation/main.js:74:2
[2018-03-06 12:50:27.298] [E] [core] result: Error: Error: Uncaught ReferenceError: WebServer is not defined
    at Error (native)
    at automation/main.js:74:2
```

**Comment by pakastin** [comment]
I think I'll just return the Razberry. 😕

**Comment by PoltoS** [comment]
Please use Jessie

**Comment by PoltoS** [comment]
Stretch is planned (we will soon switch to .deb packages)

**Comment by pakastin** [comment]
Ok, great! 👍

**Comment by RandomReaper** [comment]
Has someone a workaround for "result: Error: Error: Uncaught ReferenceError: WebServer is not defined"? or a testing version for stretch?

**Comment by pakastin** [comment]
Only way I got z-way to work was to use the image

**Comment by paulheijman** [comment]
@RandomReaper I had the same problem on my system with HomeAssistant (Debian 9.4)
Here's how I got it to work:
`cd \tmp`
`wget http://mirrordirector.raspbian.org/raspbian/pool/main/o/openssl/libssl1.0.0_1.0.1t-1+deb8u7_armhf.deb`
`dpkg -x libssl1.0.0_1.0.1t-1+deb8u7_armhf.deb .`
`mv usr/lib/arm-linux-gnueabihf/lib* /opt/z-way-server/libs/`
Be sure to include the dot (.) in the third command

**Comment by pakastin** [comment]
The bigger issue I had was that with Raspberry 3 model B, Razberry switches bluetooth off completely. Luckily I have the old Raspberry 1 model B, but I hope Bluetooth issue gets fixed to the new Raspberries as well.

**Comment by RandomReaper** [comment]
@paulheijman, thank you, that fixed this issue.

**Comment by rickybloomfield** [comment]
@PoltoS do you have a timeline for when this will be fixed? I just ordered a Razberry and am just now seeing this issue. Using Jessie isn't an option.

**Comment by pakastin** [comment]
Would it eventually be possible to use Razberry with bluetooth?

**Comment by marcelfischer** [comment]
Hey, any news on this? Installing z-way on Stretch?

**Comment by stefan-wegener** [comment]
Bumping this issue, as it is still really annoying.

**Comment by stefan-wegener** [comment]
Thanks @paulheijman for your workaround!
The only thing i noticed is that the names changed slightly and now the correct URL is: _http://mirrordirector.raspbian.org/raspbian/pool/main/o/openssl/libssl1.0.0_1.0.1t-1+deb8u8_armhf.deb_

**Comment by BrianAker** [comment]
Latest version:
http://mirrordirector.raspbian.org/raspbian/pool/main/o/openssl/libssl1.0.0_1.0.1t-1+deb8u9_armhf.deb

**Comment by PoltoS** [comment]
The latest 2.3.8-rc6 now exists in .deb package. It fixes the stretch problem. We will release it soon as 2.3.8 stable

**Comment by seanfarmar** [comment]
Thanks, @paulheijman for your workaround!
