### ISSUE TITLE
Random crashes/memory corruption

### ISSUE THREAD

**Issue by Alex895** [Z-Wave-Me/z-way-issues#137]
v3.0.0-rc12 have stable crash with message
*** Error in `/opt/z-way-server/z-way-server': corrupted size vs. prev_size: 0xb30a44a8 ***
work time from 12 hours to 3-4 days

```
root@raspberrypi:/opt/z-way-server# ./start_dbg.sh
GNU gdb (Raspbian 7.12-6) 7.12.0.20161007-git

Type "apropos word" to search for commands related to "word"...
Reading symbols from ./z-way-server...(no debugging symbols found)...done.
(gdb) r
Starting program: /opt/z-way-server/z-way-server
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/arm-linux-gnueabihf/libthread_db.so.1".

Z-Way version v3.0.0-rc12 from 2018-01-17 12:41:49 +0300 (build c547e7c37cd95ea0fe82a00a22642ea6ebb9b3c0)
Looking for modules in ./modules
Module modhttp.so loaded
Module modcrypto.so loaded
Module modws.so loaded
Module modzwave.so loaded
Module modsockets.so loaded
Module modhomekit.so loaded
Module modnotification2ext.so loaded
Module modinstaller.so loaded
Module modiconinstaller.so loaded
Module moddhs.so loaded
Module modskininstaller.so loaded
Module modenocean.so loaded
Module modzbw.so loaded
Using default configuration file config.xml
Error: 'debug-port' number is out of range. Skipping it.
[New Thread 0xb5046450 (LWP 1677)]
[New Thread 0xb5036450 (LWP 1678)]
[New Thread 0xb44ff450 (LWP 1679)]
[New Thread 0xb3aff450 (LWP 1680)]
[New Thread 0xb2eff450 (LWP 1681)]
[New Thread 0xb24ff450 (LWP 1682)]
[New Thread 0xb1cff450 (LWP 1683)]
[Thread 0xb24ff450 (LWP 1682) exited]
[Thread 0xb1cff450 (LWP 1683) exited]
[New Thread 0xb1cff450 (LWP 1700)]
[New Thread 0xb24ff450 (LWP 1701)]
[Thread 0xb24ff450 (LWP 1701) exited]
[Thread 0xb1cff450 (LWP 1700) exited]
[New Thread 0xb1cff450 (LWP 4681)]
*** Error in `/opt/z-way-server/z-way-server': corrupted size vs. prev_size: 0xb30a44a8 ***

Thread 1143 "zway/core" received signal SIGABRT, Aborted.
[Switching to Thread 0xb1cff450 (LWP 4681)]
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
51	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0xb631f824 in __GI_abort () at abort.c:89
#2  0xb6358f78 in __libc_message (do_abort=do_abort@entry=2, fmt=<optimized out>) at ../sysdeps/posix/libc_fatal.c:175
#3  0xb635fad4 in malloc_printerr (action=<optimized out>, str=0xb6411f94 "corrupted size vs. prev_size", ptr=<optimized out>, ar_ptr=<optimized out>) at malloc.c:5049
#4  0xb635ff60 in malloc_consolidate (av=av@entry=0xb3b00010) at malloc.c:4213
#5  0xb63622e4 in _int_malloc (av=av@entry=0xb3b00010, bytes=bytes@entry=35048) at malloc.c:3488
#6  0xb6364e84 in __libc_calloc (n=<optimized out>, elem_size=<optimized out>) at malloc.c:3274
#7  0xb62608f0 in ?? () from /usr/lib/arm-linux-gnueabihf/libcurl.so.4
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
(gdb) info thread
  Id   Target Id         Frame
  1    Thread 0xb62da000 (LWP 1674) "z-way-server" 0xb638f050 in nanosleep () at ../sysdeps/unix/syscall-template.S:84
  2    Thread 0xb5046450 (LWP 1677) "v8:SweeperThrea" 0xb6985014 in futex_abstimed_wait_cancelable (private=0, abstime=0x0, expected=1, futex_word=0x6c1ac)
    at ../sysdeps/unix/sysv/linux/futex-internal.h:205
  3    Thread 0xb5036450 (LWP 1678) "zway/core" 0xb638f050 in nanosleep () at ../sysdeps/unix/syscall-template.S:84
  4    Thread 0xb44ff450 (LWP 1679) "zway/webserver" 0xb638f050 in nanosleep () at ../sysdeps/unix/syscall-template.S:84
  5    Thread 0xb3aff450 (LWP 1680) "zway/timers" 0xb638f050 in nanosleep () at ../sysdeps/unix/syscall-template.S:84
  6    Thread 0xb2eff450 (LWP 1681) "zway/core" 0xb63bd2a4 in select () at ../sysdeps/unix/syscall-template.S:84
* 1143 Thread 0xb1cff450 (LWP 4681) "zway/core" __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
(gdb)

--------------------------------------------------------------------
 1672 pts/0    S+     0:23 gdb ./z-way-server
 1674 pts/0    tl   222:34 /opt/z-way-server/z-way-server
 2043 pts/0    S      0:00 /opt/z-way-server/z-way-server
 2216 pts/0    S      0:00 /opt/z-way-server/z-way-server


top - 22:53:51 up 2 days, 21:40,  2 users,  load average: 0.03, 0.07, 0.08
Tasks:   4 total,   0 running,   3 sleeping,   0 stopped,   0 zombie
%Cpu(s):  0.3 us,  0.0 sy,  0.0 ni, 99.3 id,  0.0 wa,  0.0 hi,  0.3 si,  0.0 st
KiB Mem :   444536 total,    36644 free,   134248 used,   273644 buff/cache
KiB Swap:        0 total,        0 free,        0 used.   248744 avail Mem

  PID USER      PR  NI    VIRT    RES    SHR S %CPU %MEM     TIME+ COMMAND
 1672 root      20   0   81448  74992  12740 S  0.0 16.9   0:23.93 gdb
 1674 root      20   0  144140  42112  19440 t  0.0  9.5 222:34.12 z-way-server
 2043 root      20   0  123656  21908   3480 S  0.0  4.9   0:00.00 zway/webserver
 2216 root      20   0  141064  25140   3480 S  0.0  5.7   0:00.00 zway/webserver

-----------------------------------------------------------------------------

root@raspberrypi:/ramlog# tail -f z-way-server.log -n 20
[2018-01-20 21:43:50.216] [D] [zway] SETDATA controller.data.statistics.backgroundRSSI.channel2 = 162 (0x000000a2)
[2018-01-20 21:43:50.216] [D] [zway] SETDATA controller.data.statistics.backgroundRSSI.channel3 = 127 (0x0000007f)
[2018-01-20 21:43:50.217] [I] [zway] Job 0x3b (Get background noise level): RSSI Ch#1: -94 dBm, Ch#2: -94 dBm, Ch#3: invalid
[2018-01-20 21:43:50.217] [D] [zway] Job 0x3b (Get background noise level): success
[2018-01-20 21:43:50.219] [I] [zway] Removing job: Get background noise level
[2018-01-20 21:44:10.580] [D] [zway] Job 0x3b: deleted from queue
[2018-01-20 21:44:15.961] [I] [zway] Adding job: Get statistics gathered by the Z-Wave protocol
[2018-01-20 21:44:15.966] [D] [zway] SENDING: ( 01 03 00 3A C6 )
[2018-01-20 21:44:15.970] [D] [zway] RECEIVED ACK
[2018-01-20 21:44:15.972] [D] [zway] RECEIVED: ( 01 0F 01 3A 02 CD 00 00 02 CC 00 0E 00 00 00 00 C4 )
[2018-01-20 21:44:15.974] [D] [zway] SENT ACK
[2018-01-20 21:44:15.976] [D] [zway] SETDATA controller.data.statistics.RFTxFrames = 717 (0x000002cd)
[2018-01-20 21:44:15.977] [D] [zway] SETDATA controller.data.statistics.RFTxLBTBackOffs = 0 (0x00000000)
[2018-01-20 21:44:15.978] [D] [zway] SETDATA controller.data.statistics.RFRxFrames = 716 (0x000002cc)
[2018-01-20 21:44:15.979] [D] [zway] SETDATA controller.data.statistics.RFRxLRCErrors = 14 (0x0000000e)
[2018-01-20 21:44:15.979] [D] [zway] SETDATA controller.data.statistics.RFRxCRC16Errors = 0 (0x00000000)
[2018-01-20 21:44:15.980] [D] [zway] SETDATA controller.data.statistics.RFRxForeignHomeID = 0 (0x00000000)
[2018-01-20 21:44:15.980] [I] [zway] Job 0x3a (Get statistics gathered by the Z-Wave protocol): Done
[2018-01-20 21:44:15.982] [D] [zway] Job 0x3a (Get statistics gathered by the Z-Wave protocol): success
[2018-01-20 21:44:15.984] [I] [zway] Removing job: Get statistics gathered by the Z-Wave protocol
---------------------------------
# uname -a
Linux raspberrypi 4.9.59+ #1047 Sun Oct 29 11:47:10 GMT 2017 armv6l GNU/Linux
```

more logs:
[crash3.txt](https://github.com/Z-Wave-Me/z-way-issues/files/1674714/crash3.txt)
[crash4.txt](https://github.com/Z-Wave-Me/z-way-issues/files/1674716/crash4.txt)

this crash after last libcurl update, looks little different
[crash5.txt](https://github.com/Z-Wave-Me/z-way-issues/files/1674717/crash5.txt)

**Comment by PoltoS** [comment]
Please open if still relevant
