### ISSUE TITLE
mqtt module fails

### ISSUE THREAD

**Issue by stef** [Z-Wave-Me/z-way-issues#166]
I'm trying to activate the new MQTT client app, but it fails and in the logfile i see this:

```
[2021-09-29 22:19:49.545] [I] [core] --- Starting module MQTT Client
[2021-09-29 22:19:49.702] [I] [core] Notification: error (core): Cannot instantiate module: MQTTClient: ReferenceError: mqtt is not defined
[2021-09-29 22:19:49.827] [I] [core] ReferenceError: mqtt is not defined
    at MQTTClient.init (automation/modules/MQTTClient/index.js:43:16)
    at AutomationController.instantiateModule (automation/classes/AutomationController.js:488:13)
    at AutomationController.createInstance (automation/classes/AutomationController.js:928:17)
    at ZAutomationAPIWebRequest._.extend.createInstance (automation/ZAutomationAPIProvider.js:1340:31)
    at ZAutomationAPIWebRequest.ZAutomationWebRequest.handleRequest (automation/WebserverRequestRouter.js:250:35)
    at automation/WebserverRequestRouter.js:32:29
    at WebServer.document_root (automation/Webserver.js:40:31)
```

**Comment by stef** [comment]
it turns out z-way comes with its own libmosquitto.so, i fixed this by renaming `/etc/ld.so.conf.d/z-way.conf` to `/etc/ld.so.conf.d/00-z-way.conf` and then running `ldconfig` and restarting the server.
