### ISSUE TITLE
TypeError at z-wave-server start

### ISSUE THREAD

**Issue by Vebryn** [Z-Wave-Me/z-way-issues#66]
Hi,

I open a new case about issue from aivs. I encount same thing with latest version available : z-way-server-RaspberryPiXTools-v2.1.2-rc2

[2015-05-01 00:29:23.725] [I] [core] --- Loading ZAutomation classes
[2015-05-01 00:29:23.972] [I] [core] Starting ZWay Automation webserver
[2015-05-01 00:29:23.989] [I] [core] Loading modules...
[2015-05-01 00:29:24.017] [I] [core] Loading module SecurityMode from modules/SecurityMode
[2015-05-01 00:29:24.023] [I] [core] Executing script: /**\* SecurityMode Z-Way HA module ******************************************\* ...
[2015-05-01 00:29:24.124] [E] [core] result: Error: TypeError: Cannot read property 'filter' of undefined
    at AutomationController.loadModule (automation/classes/AutomationController.js:397:19)
    at AutomationController.<anonymous> (automation/classes/AutomationController.js:439:14)
    at Array.forEach (native)
    at AutomationController.instantiateModules (automation/classes/AutomationController.js:438:46)
    at AutomationController.start (automation/classes/AutomationController.js:154:10)
    at automation/main.js:90:16

Issue from aivs : https://github.com/Z-Wave-Me/home-automation/issues/258

**Comment by Vebryn** [comment]
Problem solved, version 2.1.1 is working fine with some prerequisites:
- libarchive12 (only available from wheezy raspbian)
- libxml2

Z-Way-Server is working fine after installing these dependencies. New GUI accessed by 8083 port is nice.
